# .github/workflows/build-push.yml
name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string
      overwrite_tag:
        description: 'Do you want to overwrite the tag?'
        required: true
        type: string
      dockerhub_username:
        description: 'Docker Hub Username'
        required: true
        type: string
      dockerhub_password:
        description: 'Docker Hub Password'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_password }}

      - name: Build Docker image
        run: |
          docker build -t "${{ inputs.image_tag }}" -t "${{ inputs.image_tag }}:latest" .

      - name: Check if the tag exists on Docker Hub
        run: |
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/${{ inputs.dockerhub_username }}/zsh/tags/${{ inputs.image_tag }}")
          if [ "$TAG_EXISTS" -eq 200 ] && [ "${{ inputs.overwrite_tag }}" != "true" ]; then
              echo "Tag already exists and overwrite is not allowed. Skipping push."
              exit 0
          fi

      - name: Push Docker image
        run: |
          echo "Pushing the Docker image..."
          docker push "${{ inputs.image_tag }}"
          docker push "${{ inputs.image_tag }}:latest"
